// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../..
// from ../../gir-files
// DO NOT EDIT

#include "manual.h"
#include <stdio.h>

#define PRINT_CONSTANT(CONSTANT_NAME) \
    printf("%s;", #CONSTANT_NAME); \
    printf(_Generic((CONSTANT_NAME), \
                    char *: "%s", \
                    const char *: "%s", \
                    char: "%c", \
                    signed char: "%hhd", \
                    unsigned char: "%hhu", \
                    short int: "%hd", \
                    unsigned short int: "%hu", \
                    int: "%d", \
                    unsigned int: "%u", \
                    long: "%ld", \
                    unsigned long: "%lu", \
                    long long: "%lld", \
                    unsigned long long: "%llu", \
                    float: "%f", \
                    double: "%f", \
                    long double: "%ld"), \
           CONSTANT_NAME); \
    printf("\n");

int main() {
    PRINT_CONSTANT(CLOUD_PROVIDERS_ACCOUNT_DBUS_IFACE);
    PRINT_CONSTANT((gint) CLOUD_PROVIDERS_ACCOUNT_STATUS_ERROR);
    PRINT_CONSTANT((gint) CLOUD_PROVIDERS_ACCOUNT_STATUS_IDLE);
    PRINT_CONSTANT((gint) CLOUD_PROVIDERS_ACCOUNT_STATUS_INVALID);
    PRINT_CONSTANT((gint) CLOUD_PROVIDERS_ACCOUNT_STATUS_SYNCING);
    PRINT_CONSTANT(CLOUD_PROVIDERS_PROVIDER_DBUS_IFACE);
    return 0;
}
