// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../..
// from ../../gir-files
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "CloudProvidersAccountClass", sizeof(CloudProvidersAccountClass), alignof(CloudProvidersAccountClass));
    printf("%s;%zu;%zu\n", "CloudProvidersAccountExporterClass", sizeof(CloudProvidersAccountExporterClass), alignof(CloudProvidersAccountExporterClass));
    printf("%s;%zu;%zu\n", "CloudProvidersAccountStatus", sizeof(CloudProvidersAccountStatus), alignof(CloudProvidersAccountStatus));
    printf("%s;%zu;%zu\n", "CloudProvidersCollectorClass", sizeof(CloudProvidersCollectorClass), alignof(CloudProvidersCollectorClass));
    printf("%s;%zu;%zu\n", "CloudProvidersDbusAccountIface", sizeof(CloudProvidersDbusAccountIface), alignof(CloudProvidersDbusAccountIface));
    printf("%s;%zu;%zu\n", "CloudProvidersDbusAccountProxy", sizeof(CloudProvidersDbusAccountProxy), alignof(CloudProvidersDbusAccountProxy));
    printf("%s;%zu;%zu\n", "CloudProvidersDbusAccountProxyClass", sizeof(CloudProvidersDbusAccountProxyClass), alignof(CloudProvidersDbusAccountProxyClass));
    printf("%s;%zu;%zu\n", "CloudProvidersDbusAccountSkeleton", sizeof(CloudProvidersDbusAccountSkeleton), alignof(CloudProvidersDbusAccountSkeleton));
    printf("%s;%zu;%zu\n", "CloudProvidersDbusAccountSkeletonClass", sizeof(CloudProvidersDbusAccountSkeletonClass), alignof(CloudProvidersDbusAccountSkeletonClass));
    printf("%s;%zu;%zu\n", "CloudProvidersDbusObjectIface", sizeof(CloudProvidersDbusObjectIface), alignof(CloudProvidersDbusObjectIface));
    printf("%s;%zu;%zu\n", "CloudProvidersDbusObjectManagerClient", sizeof(CloudProvidersDbusObjectManagerClient), alignof(CloudProvidersDbusObjectManagerClient));
    printf("%s;%zu;%zu\n", "CloudProvidersDbusObjectManagerClientClass", sizeof(CloudProvidersDbusObjectManagerClientClass), alignof(CloudProvidersDbusObjectManagerClientClass));
    printf("%s;%zu;%zu\n", "CloudProvidersDbusObjectProxy", sizeof(CloudProvidersDbusObjectProxy), alignof(CloudProvidersDbusObjectProxy));
    printf("%s;%zu;%zu\n", "CloudProvidersDbusObjectProxyClass", sizeof(CloudProvidersDbusObjectProxyClass), alignof(CloudProvidersDbusObjectProxyClass));
    printf("%s;%zu;%zu\n", "CloudProvidersDbusObjectSkeleton", sizeof(CloudProvidersDbusObjectSkeleton), alignof(CloudProvidersDbusObjectSkeleton));
    printf("%s;%zu;%zu\n", "CloudProvidersDbusObjectSkeletonClass", sizeof(CloudProvidersDbusObjectSkeletonClass), alignof(CloudProvidersDbusObjectSkeletonClass));
    printf("%s;%zu;%zu\n", "CloudProvidersDbusProviderIface", sizeof(CloudProvidersDbusProviderIface), alignof(CloudProvidersDbusProviderIface));
    printf("%s;%zu;%zu\n", "CloudProvidersDbusProviderProxy", sizeof(CloudProvidersDbusProviderProxy), alignof(CloudProvidersDbusProviderProxy));
    printf("%s;%zu;%zu\n", "CloudProvidersDbusProviderProxyClass", sizeof(CloudProvidersDbusProviderProxyClass), alignof(CloudProvidersDbusProviderProxyClass));
    printf("%s;%zu;%zu\n", "CloudProvidersDbusProviderSkeleton", sizeof(CloudProvidersDbusProviderSkeleton), alignof(CloudProvidersDbusProviderSkeleton));
    printf("%s;%zu;%zu\n", "CloudProvidersDbusProviderSkeletonClass", sizeof(CloudProvidersDbusProviderSkeletonClass), alignof(CloudProvidersDbusProviderSkeletonClass));
    printf("%s;%zu;%zu\n", "CloudProvidersProviderClass", sizeof(CloudProvidersProviderClass), alignof(CloudProvidersProviderClass));
    printf("%s;%zu;%zu\n", "CloudProvidersProviderExporterClass", sizeof(CloudProvidersProviderExporterClass), alignof(CloudProvidersProviderExporterClass));
    return 0;
}
